export default {
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '1f391b9e': [() => import(/* webpackChunkName: '1f391b9e' */ '@theme/MDXPage'), '@theme/MDXPage', require.resolveWeak('@theme/MDXPage')],
  '208b50aa': [() => import(/* webpackChunkName: '208b50aa' */ '@site/docs/personal/tracking.md'), '@site/docs/personal/tracking.md', require.resolveWeak('@site/docs/personal/tracking.md')],
  '393be207': [() => import(/* webpackChunkName: '393be207' */ '@site/src/pages/markdown-page.md'), '@site/src/pages/markdown-page.md', require.resolveWeak('@site/src/pages/markdown-page.md')],
  '5bfc32c8': [() => import(/* webpackChunkName: '5bfc32c8' */ '@site/i18n/de/docusaurus-plugin-content-docs/current/intro.md'), '@site/i18n/de/docusaurus-plugin-content-docs/current/intro.md', require.resolveWeak('@site/i18n/de/docusaurus-plugin-content-docs/current/intro.md')],
  '6180fec9': [() => import(/* webpackChunkName: '6180fec9' */ '/Users/v4/Source Code/ginnywiki/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json'), '/Users/v4/Source Code/ginnywiki/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/v4/Source Code/ginnywiki/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json')],
  '78f36d09': [() => import(/* webpackChunkName: '78f36d09' */ '/Users/v4/Source Code/ginnywiki/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json'), '/Users/v4/Source Code/ginnywiki/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/v4/Source Code/ginnywiki/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],};
